name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: gcc vuln.c -o vuln -fno-stack-protector -z execstack -mpreferred-stack-boundary=2
